#include <algorithm>
#include <axiom/codegen/cpp_generator.hpp>
#include <fmt/format.h>
#include <unordered_set>
#include <vector>

namespace axiom::codegen
{

std::string CppGenerator::sanitize_symbol(std::string_view name) const
{
    return std::string(name);
}

core::Result<GeneratedUnit> CppGenerator::generate(const ast::TranslationUnit& unit,
                                                   const semantic::SemanticModel& model) const
{
    (void)model;
    GeneratedUnit generated{};
    for (const auto& machine : unit.machines)
    {
        const auto part = generate_machine(machine);
        for (const auto& file : part.files)
        {
            generated.files.push_back(file);
        }
    }
    return core::Result<GeneratedUnit>::ok(std::move(generated));
}

GeneratedUnit CppGenerator::generate_machine(const ast::MachineDecl& machine) const
{
    const std::string machine_name = sanitize_symbol(machine.name);

    std::string header = fmt::format("#pragma once\n\n"
                                     "// Generated by Axiom — do not edit.\n\n"
                                     "#include <cstdint>\n\n"
                                     "namespace axiom::generated::{} {{\n\n"
                                     "enum class State : std::uint8_t {{\n",
                                     machine_name);

    for (std::size_t i = 0; i < machine.states.size(); ++i)
    {
        const auto& state = machine.states[i];
        header += fmt::format("  {},\n", sanitize_symbol(state.name));
    }
    header += "};\n\n";

    std::vector<std::string> events;
    {
        std::unordered_set<std::string> seen;
        for (const auto& transition : machine.transitions)
        {
            if (seen.insert(transition.event_name).second)
            {
                events.push_back(transition.event_name);
            }
        }
        std::sort(events.begin(), events.end());
    }

    if (!events.empty())
    {
        header += "enum class Event : std::uint8_t {\n";
        std::size_t event_index = 0;
        for (const auto& event_name : events)
        {
            header += fmt::format("  {} = {},\n", sanitize_symbol(event_name), event_index++);
        }
        header += "};\n\n";
    }

    header += fmt::format("[[nodiscard]] State initial_state();\n"
                          "[[nodiscard]] State transition(State current, Event event);\n\n"
                          "}} // namespace axiom::generated::{}\n",
                          machine_name);

    std::string source = fmt::format("#include \"{}.hpp\"\n\n"
                                     "namespace axiom::generated::{} {{\n\n",
                                     machine_name, machine_name);

    if (!machine.states.empty())
    {
        source += fmt::format("State initial_state() {{\n"
                              "  return State::{};\n"
                              "}}\n\n",
                              sanitize_symbol(machine.states.front().name));
    }
    else
    {
        source += "State initial_state() {\n  return State{};\n}\n\n";
    }

    if (!events.empty())
    {
        source += fmt::format("State transition(State current, Event event) {{\n"
                              "  switch (current) {{\n");

        for (const auto& state : machine.states)
        {
            source += fmt::format("  case State::{}:\n", sanitize_symbol(state.name));
            source += "    switch (event) {\n";

            bool any = false;
            for (const auto& transition : machine.transitions)
            {
                if (transition.source_state != state.name)
                {
                    continue;
                }
                any = true;
                source += fmt::format("    case Event::{}:\n"
                                      "      return State::{};\n",
                                      sanitize_symbol(transition.event_name),
                                      sanitize_symbol(transition.target_state));
            }
            if (!any)
            {
                source += "    default:\n      break;\n";
            }
            else
            {
                source += "    default:\n      break;\n";
            }
            source += "    }\n    break;\n";
        }

        source += "  default:\n    break;\n  }\n  return current;\n}\n\n";
    }
    else
    {
        source += "State transition(State current, Event) {\n  return current;\n}\n\n";
    }

    source += fmt::format("}} // namespace axiom::generated::{}\n", machine_name);

    GeneratedUnit unit{};
    unit.files.push_back(GeneratedFile{fmt::format("{}.hpp", machine_name), std::move(header)});
    unit.files.push_back(GeneratedFile{fmt::format("{}.cpp", machine_name), std::move(source)});
    return unit;
}

} // namespace axiom::codegen
